
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <title>Document</title>
        <style>
        .question {
        border: 5px cornflowerblue solid;
        border-radius: 15px;
        padding: 10px;
        font-size: 24px;
        color: cornflowerblue;
        text-align: center;
    }</style>
        <style>
        .answer {
        width: fit-content;
        margin-left: auto;
        margin-right: auto;
        border: 1px orange solid;
        border-radius: 5px;
        padding: 20px;
        font-size: 20px;
        color: black;
    }</style>
    </head>
    <body>
        
            <p class="question">01.yml&nbsp;Q:&amp;nbsp;介绍一些Java的异常接口&lt;br&gt;</p>
        
            <p class="answer">A:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;Throwable:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;异常的顶级父类,表示所有非正常情况&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;有两个直接子类Error和Exception&lt;br&gt;&amp;nbsp;&amp;nbsp;Error:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;表示程序的严重错误(编译,连接,虚拟机,系统崩溃)&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;不可throw,不可try,不可catch&lt;br&gt;&amp;nbsp;&amp;nbsp;Exception:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;表示程序运行过程中(可预料的,可修复的)意外情况&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;分为Checked异常和Runtime异常&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;Checked异常:&amp;nbsp;必须显式throw或catch或throws,否则无法通过编译&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;Runtime异常:&amp;nbsp;无需显式捕获,该崩就崩(记录日志排查错误)</p>
        
            <p class="question">02.yml&nbsp;Q:&amp;nbsp;说说如何处理Java中的异常&lt;br&gt;</p>
        
            <p class="answer">A:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;抛出异常:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;JVM自身、native方法可自动抛出异常&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;当错误条件成立时可throw异常,或throws异常&lt;br&gt;&amp;nbsp;&amp;nbsp;捕获异常:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;将业务代码放在try块中&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;当代码发生异常时,系统自动创建异常对象,分配到catch子句中处理&lt;br&gt;&amp;nbsp;&amp;nbsp;处理异常:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;定义多个catch子句作为handler承接处理异常对象&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;catch应对其溯源,然后根据需求赋默认值或null&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;对于不能catch的则向外抛&lt;br&gt;&amp;nbsp;&amp;nbsp;回收资源:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;业务代码会打开一些资源(数据库连接、网络连接、文件)&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;若碰到异常则无法顺利关闭这些资源&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;通过finally子句,不管有无异常都保证finally执行以关闭资源</p>
        
            <p class="question">03.yml&nbsp;Q:&amp;nbsp;说说Java中异常的详细处理过程&lt;br&gt;</p>
        
            <p class="answer">A:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;代码块:&amp;nbsp;[初始块,静态块,属性接匿名实现,方法体]&lt;br&gt;&amp;nbsp;&amp;nbsp;异常语句:&amp;nbsp;[throw语句,调用带throws的方法]&lt;br&gt;&amp;nbsp;&amp;nbsp;引起中断:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;return:&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;在try或catch里,则执行finally结束&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;在finally里,结束&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;throw(s):&amp;nbsp;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;有catch,则依次e&amp;nbsp;instanceof&amp;nbsp;xxExceptopn,交给对应catch子句处理&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;无catch,则执行finally结束(已经在finally里则直接结束)&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;System.exit:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;-&amp;nbsp;直接杀死JVM,没有后续了</p>
        
    </body>
    </html>
